<div class="space-y-5">
    @php $statuses = ['open'=>'Abierta','in_progress'=>'En gestión','resolved'=>'Resuelta','ignored'=>'Descartada','suspended'=>'Suspendida','superseded'=>'Sustituida']; $kinds = ['detected'=>'Detectada','resolved'=>'Recuperación','state_changed'=>'Cambio de estado Meta','notified'=>'Aviso entregado','read'=>'Lectura','acknowledged'=>'Confirmación','status_changed'=>'Gestión','suspended'=>'Entidad fuera del alcance','superseded'=>'Nueva configuración o agrupación']; @endphp
    <div class="flex flex-wrap gap-3 items-end"><h2 class="text-xl font-semibold mr-auto">Historial de incidencias</h2><label class="text-sm">Cliente<select wire:model.live="customerId" class="block mt-1 rounded-xl border-white/20 bg-slate-900 text-white"><option value="">Todos</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }}</option>@endforeach</select></label><label class="text-sm">Estado<select wire:model.live="status" class="block mt-1 rounded-xl border-white/20 bg-slate-900 text-white"><option value="">Todos</option>@foreach($statuses as $code=>$label)<option value="{{ $code }}">{{ $label }}</option>@endforeach</select></label></div>
    <div class="rounded-2xl border border-white/10 bg-slate-950/30 overflow-x-auto"><table class="w-full text-sm text-left"><thead class="text-white/60 bg-white/5"><tr><th class="p-4">Incidencia</th><th class="p-4">Cliente</th><th class="p-4">Estado</th><th class="p-4">Detectada</th><th class="p-4">Detalle</th></tr></thead><tbody class="divide-y divide-white/10">@forelse($items as $item)<tr wire:key="alert-{{ $item->id }}"><td class="p-4">#{{ $item->id }} · {{ $item->type->name }}<p class="text-xs text-white/50">{{ $item->entity_name }} · {{ $item->entity_id }}</p></td><td class="p-4">{{ $item->customer_name }}</td><td class="p-4">{{ $statuses[$item->status] ?? $item->status }}</td><td class="p-4">{{ $item->detected_at->format('d/m/Y H:i') }}</td><td class="p-4"><button type="button" wire:click="open({{ $item->id }})" class="rounded-lg border border-white/20 px-3 py-1.5 hover:bg-white/10">Ver historial</button></td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-white/60">No se han encontrado incidencias.</td></tr>@endforelse</tbody></table></div>{{ $items->links() }}
    @if($selected)
        <section class="rounded-2xl border border-white/10 bg-slate-950/30 p-5 space-y-4">
            <div class="flex justify-between"><h3 class="text-lg font-semibold">Incidencia #{{ $selected->id }}</h3><button type="button" wire:click="close" class="text-sm underline">Cerrar</button></div>
            <p class="text-xs text-white/50">{{ $selected->type->subcategory->category->name }} → {{ $selected->type->subcategory->name }}</p>
            <p>{{ $selected->message }}</p><p class="text-sm text-white/60">{{ isset($selected->metadata['metric_subscription_id']) ? 'Estado de la medición' : 'Estado actual Meta' }}: {{ $selected->current_state }} · Última observación: {{ $selected->last_seen_at->format('d/m/Y H:i') }}@if($selected->previous_alert_id) · Reincidencia de #{{ $selected->previous_alert_id }}@endif</p>
            @if (isset($selected->metadata['metric_subscription_id']))
                <div class="space-y-2 text-sm">@foreach ($selected->metadata['rows'] as $measurement)<div class="rounded-xl border border-white/10 p-3"><p>{{ strtoupper($measurement['platform']) }} · {{ $measurement['name'] }} · {{ $measurement['count'] }} / mínimo {{ $measurement['threshold'] }}</p><p class="mt-1 text-xs text-white/60">{{ $measurement['window_start'] }} → {{ $measurement['window_end'] }} (fin exclusivo)</p></div>@endforeach</div>
            @endif
            @if(!$selected->resolved_at && (!isset($selected->metadata['metric_subscription_id']) || $selected->active_key))
                <div class="space-y-2"><label for="alert-reason" class="text-sm">Motivo de la gestión</label><input id="alert-reason" wire:model="reason" maxlength="2000" class="w-full rounded-xl border-white/20 bg-slate-900 text-white">@error('reason')<p class="text-rose-200 text-sm">{{ $message }}</p>@enderror<div class="flex flex-wrap gap-2"><button type="button" wire:click="changeStatus('in_progress')" class="rounded-xl border border-white/20 px-3 py-2">Marcar en gestión</button><button type="button" wire:click="changeStatus('ignored')" class="rounded-xl border border-white/20 px-3 py-2">Descartar avisos futuros</button><button type="button" wire:click="changeStatus('open')" class="rounded-xl border border-white/20 px-3 py-2">Restablecer avisos</button></div><p class="text-xs text-white/50">La recuperación se confirma con Meta. Descartar no confirma las respuestas de los usuarios.</p></div>
            @endif
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-5">
                <div><h4 class="font-semibold mb-3">Actividad</h4><ol class="space-y-2 max-h-96 overflow-auto">@foreach($selected->events->sortByDesc('id') as $event)<li class="border-l border-white/20 pl-3 text-sm"><p>{{ $kinds[$event->kind] ?? $event->kind }} · {{ $event->occurred_at->format('d/m/Y H:i') }} @if($event->user)· {{ $event->user->name }}@endif</p>@if(data_get($event->data,'current'))<p class="text-white/60">{{ data_get($event->data,'previous') }} → {{ data_get($event->data,'current') }}</p>@endif @if(data_get($event->data,'reason'))<p class="text-white/70 break-words">{{ $event->data['reason'] }}</p>@endif @if(data_get($event->data,'sequence'))<p class="text-white/60">Aviso {{ $event->data['sequence'] }} · usuario #{{ $event->data['user_id'] }}</p>@endif</li>@endforeach</ol></div>
                <div><h4 class="font-semibold mb-3">Destinatarios y respuestas</h4><div class="space-y-3">@forelse($selected->recipients as $recipient)<div class="rounded-xl border border-white/10 p-3 text-sm"><p class="font-medium">{{ $recipient->user?->name }}</p><p class="text-white/60">{{ $recipient->notification_count }} aviso(s) · {{ $recipient->read_at ? 'Leída' : 'No leída' }} · {{ $recipient->acknowledged_at ? 'Confirmada' : ($recipient->requires_response ? 'Respuesta pendiente' : 'Sin respuesta obligatoria') }}</p>@foreach($recipient->comments as $comment)<p class="mt-2 whitespace-pre-wrap break-words">{{ $comment->body }}</p><p class="text-xs text-white/50">{{ $comment->created_at->format('d/m/Y H:i') }}</p>@endforeach</div>@empty<p class="text-sm text-white/60">Aún no se ha notificado. Puede no haber una regla aplicable o estar pendiente del horario, umbral o destinatarios.</p>@endforelse</div></div>
            </div>
        </section>
    @endif
</div>
