<div class="space-y-5">
    @php $input = 'mt-1 w-full rounded-xl border-white/20 bg-slate-900 text-white text-sm'; @endphp
    <div class="flex flex-wrap justify-between gap-3"><div><h2 class="text-xl font-semibold">Reglas por cliente</h2><p class="text-sm text-white/70">Las reglas de tipo tienen prioridad sobre subcategoría y categoría. Una regla inactiva excluye su alcance.</p></div><button type="button" wire:click="create" class="rounded-xl border border-teal-300/30 bg-teal-500/30 hover:bg-teal-500/40 px-4 py-2">+ Nueva regla</button></div>
    @if (session('alert-success'))<p role="status" class="rounded-xl bg-emerald-500/20 p-3">{{ session('alert-success') }}</p>@endif
    @if ($editing)
        <form wire:submit="save" class="rounded-2xl border border-white/10 bg-slate-950/30 p-5 space-y-5">
            <h3 class="text-lg font-semibold">{{ $editingId ? 'Editar regla' : 'Crear configuración' }}</h3>
            @if ($errors->any())<div role="alert" class="rounded-xl bg-rose-500/20 p-3 text-sm"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
            <div class="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
                <label class="md:col-span-3">Nombre<input wire:model="form.name" required maxlength="150" class="{{ $input }}"></label>
                <label>Categoría<select wire:model.live="form.category_id" class="{{ $input }}">@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></label>
                <label>Subcategoría<select wire:model.live="form.subcategory_id" class="{{ $input }}"><option value="">Toda la categoría</option>@foreach($subcategories as $subcategory)<option value="{{ $subcategory->id }}">{{ $subcategory->name }}</option>@endforeach</select></label>
                <label>Tipo de alerta<select wire:model="form.type_id" class="{{ $input }}"><option value="">Todos los tipos del alcance</option>@foreach($types as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select></label>
                <fieldset class="md:col-span-1"><legend>Clientes</legend><div class="mt-1 max-h-48 overflow-auto rounded-xl border border-white/20 bg-slate-900 p-3 space-y-2">@foreach($customers as $customer)<label class="flex items-center gap-2"><input type="checkbox" wire:model="form.customer_ids" value="{{ $customer->id }}" @disabled($editingId !== null) class="rounded border-white/30 bg-white/10 text-teal-500"><span>{{ $customer->name }}</span></label>@endforeach</div><p class="mt-1 text-xs text-white/50">Al seleccionar varios se crea una regla independiente para cada cliente.</p></fieldset>
                <fieldset class="md:col-span-2"><legend>Usuarios destinatarios</legend><div class="mt-1 max-h-48 overflow-auto rounded-xl border border-white/20 bg-slate-900 p-3 grid grid-cols-1 md:grid-cols-2 gap-2">@foreach($users as $user)<label class="flex items-center gap-2"><input type="checkbox" wire:model="form.user_ids" value="{{ $user->id }}" class="rounded border-white/30 bg-white/10 text-teal-500"><span>{{ $user->name }}</span></label>@endforeach</div></fieldset>
                <label>Zona horaria<input wire:model="form.timezone" required class="{{ $input }}" placeholder="America/Bogota"></label>
                <label>Vigente desde<input type="datetime-local" wire:model="form.starts_at" required class="{{ $input }}"></label>
                <label>Vigente hasta (opcional)<input type="datetime-local" wire:model="form.ends_at" class="{{ $input }}"><span class="text-xs text-white/50">Vacío: permanente. Fechas en la zona elegida.</span></label>
                <fieldset class="md:col-span-3"><legend class="mb-2">Días permitidos</legend><div class="flex flex-wrap gap-4">@foreach([1=>'Lunes',2=>'Martes',3=>'Miércoles',4=>'Jueves',5=>'Viernes',6=>'Sábado',7=>'Domingo'] as $day=>$label)<label class="flex items-center gap-2"><input type="checkbox" wire:model="form.weekdays" value="{{ $day }}" class="rounded border-white/30 bg-white/10 text-teal-500">{{ $label }}</label>@endforeach</div></fieldset>
                <label>Hora inicial (opcional)<input type="time" wire:model="form.starts_time" class="{{ $input }}"></label>
                <label>Hora final (opcional)<input type="time" wire:model="form.ends_time" class="{{ $input }}"></label>
                <p class="self-center text-xs text-white/60">Sin horas: todo el día. Si la hora final es menor, termina al día siguiente; se usa el día de inicio.</p>
                <label>Máximo de avisos por usuario<input type="number" min="1" max="100" wire:model="form.max_notifications" required class="{{ $input }}"><span class="text-xs text-white/50">Incluye el primer aviso y sus recordatorios.</span></label>
                <label>Intervalo mínimo (minutos)<input type="number" min="1" max="525600" wire:model="form.interval_minutes" required class="{{ $input }}"></label>
                <label>Mínimo de incidencias distintas<input type="number" min="1" max="10000" wire:model="form.min_alerts" required class="{{ $input }}"><span class="text-xs text-white/50">Del mismo cliente y alcance. Mayor que 1 puede dejar un problema aislado sin avisar.</span></label>
                <label>Severidad<select wire:model="form.severity" class="{{ $input }}"><option value="info">Informativa</option><option value="warning">Advertencia</option><option value="critical">Crítica</option></select></label>
                <label>Canal<select wire:model="form.channel" class="{{ $input }}"><option value="internal">Notificación interna</option></select></label>
                <div class="space-y-3 self-center"><label class="flex items-center gap-2"><input type="checkbox" wire:model="form.enabled" class="rounded text-teal-500">Regla activa</label><label class="flex items-center gap-2"><input type="checkbox" wire:model="form.requires_response" class="rounded text-teal-500">Exigir comentario para confirmar</label></div>
            </div>
            <div class="flex gap-3"><button wire:loading.attr="disabled" class="rounded-xl bg-teal-500/30 hover:bg-teal-500/40 border border-teal-300/30 px-5 py-2 disabled:opacity-50">Guardar configuración</button><button type="button" wire:click="$set('editing', false)" class="rounded-xl border border-white/20 px-4 py-2">Cancelar</button></div>
        </form>
    @endif
    <div class="rounded-2xl border border-white/10 bg-slate-950/30 overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-white/5 text-white/60"><tr><th class="p-4">Cliente / regla</th><th class="p-4">Alcance</th><th class="p-4">Destinatarios</th><th class="p-4">Estado</th><th class="p-4">Acción</th></tr></thead><tbody class="divide-y divide-white/10">
        @forelse($items as $rule)<tr wire:key="rule-{{ $rule->id }}"><td class="p-4"><p class="font-medium">{{ $rule->customer?->name ?? 'Cliente eliminado' }}</p><p class="text-xs text-white/60">{{ $rule->name }}</p></td><td class="p-4">{{ $rule->type?->name ?? $rule->subcategory?->name ?? $rule->category->name }}<p class="text-xs text-white/50">{{ $rule->timezone }} · {{ $rule->max_notifications }} aviso(s)</p></td><td class="p-4">{{ $rule->users->pluck('name')->join(', ') }}@if($rule->requires_response)<p class="text-xs text-amber-100">Comentario obligatorio</p>@endif</td><td class="p-4">{{ $rule->enabled ? 'Activa' : 'Inactiva' }}</td><td class="p-4"><button type="button" wire:click="edit({{ $rule->id }})" class="rounded-lg border border-white/20 px-3 py-1.5 hover:bg-white/10">Editar</button></td></tr>
        @empty<tr><td colspan="5" class="p-10 text-center text-white/60">Crea una regla para comenzar a distribuir alertas. No hay suscripciones automáticas.</td></tr>@endforelse
    </tbody></table></div>{{ $items->links() }}
</div>
